import { StyleSheet } from "react-native";
import { colors } from "../../Constant/color";
const style=StyleSheet.create({
    header:{
        marginTop:20,
        marginHorizontal:24,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between"
    },
    headerTextIntro:{
     fontFamily:"Inter",
     fontSize:16,
     fontWeight:"400",
     lineHeight:19,
     color:colors.small
    },
    userName:{
        marginTop:5
    },
    profileImage:{
        height:50,
        width:50
    },
    searchBox:{
        marginHorizontal:24,
        marginTop:20
    },
    highlightedContainer:{
        marginHorizontal:24,
    },
    highlighted:{
        width:"110%",
        height:250
    },
    category:{
        marginLeft:24,
    },
    categoryItem:{
        marginRight:10
    },
    selectCategory:{
        marginHorizontal:24,
        marginBottom:16,
        marginTop:6
    },
    donationItemcontainer:{
        marginTop:20,
        marginHorizontal:24,
        flexDirection:"row",
        justifyContent:"space-between",
        flexWrap:"wrap"
    },
    singleDonationItems:{
        maxHeight:"49%",
        marginBottom:23
    }
})
export default style